# coding: utf-8

# flake8: noqa
"""
    Argo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v2.2.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from argo.models.v1alpha1_archive_strategy import V1alpha1ArchiveStrategy
from argo.models.v1alpha1_arguments import V1alpha1Arguments
from argo.models.v1alpha1_artifact import V1alpha1Artifact
from argo.models.v1alpha1_artifact_location import V1alpha1ArtifactLocation
from argo.models.v1alpha1_artifactory_artifact import V1alpha1ArtifactoryArtifact
from argo.models.v1alpha1_artifactory_auth import V1alpha1ArtifactoryAuth
from argo.models.v1alpha1_dag_task import V1alpha1DAGTask
from argo.models.v1alpha1_dag_template import V1alpha1DAGTemplate
from argo.models.v1alpha1_git_artifact import V1alpha1GitArtifact
from argo.models.v1alpha1_http_artifact import V1alpha1HTTPArtifact
from argo.models.v1alpha1_inputs import V1alpha1Inputs
from argo.models.v1alpha1_metadata import V1alpha1Metadata
from argo.models.v1alpha1_outputs import V1alpha1Outputs
from argo.models.v1alpha1_parameter import V1alpha1Parameter
from argo.models.v1alpha1_raw_artifact import V1alpha1RawArtifact
from argo.models.v1alpha1_resource_template import V1alpha1ResourceTemplate
from argo.models.v1alpha1_retry_strategy import V1alpha1RetryStrategy
from argo.models.v1alpha1_s3_artifact import V1alpha1S3Artifact
from argo.models.v1alpha1_s3_bucket import V1alpha1S3Bucket
from argo.models.v1alpha1_script_template import V1alpha1ScriptTemplate
from argo.models.v1alpha1_sequence import V1alpha1Sequence
from argo.models.v1alpha1_sidecar import V1alpha1Sidecar
from argo.models.v1alpha1_template import V1alpha1Template
from argo.models.v1alpha1_value_from import V1alpha1ValueFrom
from argo.models.v1alpha1_workflow import V1alpha1Workflow
from argo.models.v1alpha1_workflow_list import V1alpha1WorkflowList
from argo.models.v1alpha1_workflow_spec import V1alpha1WorkflowSpec
from argo.models.v1alpha1_workflow_step import V1alpha1WorkflowStep
