# coding: utf-8

"""
    Argo

    Argo  # noqa: E501

    The version of the OpenAPI document: v2.7.5
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class V1alpha1S3Bucket(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'access_key_secret': 'kubernetes.client.models.V1SecretKeySelector',
        'bucket': 'str',
        'endpoint': 'str',
        'insecure': 'bool',
        'region': 'str',
        'role_arn': 'str',
        'secret_key_secret': 'kubernetes.client.models.V1SecretKeySelector',
        'use_sdk_creds': 'bool'
    }

    attribute_map = {
        'access_key_secret': 'accessKeySecret',
        'bucket': 'bucket',
        'endpoint': 'endpoint',
        'insecure': 'insecure',
        'region': 'region',
        'role_arn': 'roleARN',
        'secret_key_secret': 'secretKeySecret',
        'use_sdk_creds': 'useSDKCreds'
    }

    def __init__(self, access_key_secret=None, bucket=None, endpoint=None, insecure=None, region=None, role_arn=None, secret_key_secret=None, use_sdk_creds=None):  # noqa: E501
        """V1alpha1S3Bucket - a model defined in OpenAPI"""  # noqa: E501

        self._access_key_secret = None
        self._bucket = None
        self._endpoint = None
        self._insecure = None
        self._region = None
        self._role_arn = None
        self._secret_key_secret = None
        self._use_sdk_creds = None
        self.discriminator = None

        if access_key_secret is not None:
            self.access_key_secret = access_key_secret
        if bucket is not None:
            self.bucket = bucket
        if endpoint is not None:
            self.endpoint = endpoint
        if insecure is not None:
            self.insecure = insecure
        if region is not None:
            self.region = region
        if role_arn is not None:
            self.role_arn = role_arn
        if secret_key_secret is not None:
            self.secret_key_secret = secret_key_secret
        if use_sdk_creds is not None:
            self.use_sdk_creds = use_sdk_creds

    @property
    def access_key_secret(self):
        """Gets the access_key_secret of this V1alpha1S3Bucket.  # noqa: E501


        :return: The access_key_secret of this V1alpha1S3Bucket.  # noqa: E501
        :rtype: kubernetes.client.models.V1SecretKeySelector
        """
        return self._access_key_secret

    @access_key_secret.setter
    def access_key_secret(self, access_key_secret):
        """Sets the access_key_secret of this V1alpha1S3Bucket.


        :param access_key_secret: The access_key_secret of this V1alpha1S3Bucket.  # noqa: E501
        :type: kubernetes.client.models.V1SecretKeySelector
        """

        self._access_key_secret = access_key_secret

    @property
    def bucket(self):
        """Gets the bucket of this V1alpha1S3Bucket.  # noqa: E501


        :return: The bucket of this V1alpha1S3Bucket.  # noqa: E501
        :rtype: str
        """
        return self._bucket

    @bucket.setter
    def bucket(self, bucket):
        """Sets the bucket of this V1alpha1S3Bucket.


        :param bucket: The bucket of this V1alpha1S3Bucket.  # noqa: E501
        :type: str
        """

        self._bucket = bucket

    @property
    def endpoint(self):
        """Gets the endpoint of this V1alpha1S3Bucket.  # noqa: E501


        :return: The endpoint of this V1alpha1S3Bucket.  # noqa: E501
        :rtype: str
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint):
        """Sets the endpoint of this V1alpha1S3Bucket.


        :param endpoint: The endpoint of this V1alpha1S3Bucket.  # noqa: E501
        :type: str
        """

        self._endpoint = endpoint

    @property
    def insecure(self):
        """Gets the insecure of this V1alpha1S3Bucket.  # noqa: E501


        :return: The insecure of this V1alpha1S3Bucket.  # noqa: E501
        :rtype: bool
        """
        return self._insecure

    @insecure.setter
    def insecure(self, insecure):
        """Sets the insecure of this V1alpha1S3Bucket.


        :param insecure: The insecure of this V1alpha1S3Bucket.  # noqa: E501
        :type: bool
        """

        self._insecure = insecure

    @property
    def region(self):
        """Gets the region of this V1alpha1S3Bucket.  # noqa: E501


        :return: The region of this V1alpha1S3Bucket.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this V1alpha1S3Bucket.


        :param region: The region of this V1alpha1S3Bucket.  # noqa: E501
        :type: str
        """

        self._region = region

    @property
    def role_arn(self):
        """Gets the role_arn of this V1alpha1S3Bucket.  # noqa: E501

        RoleARN is the Amazon Resource Name (ARN) of the role to assume.  # noqa: E501

        :return: The role_arn of this V1alpha1S3Bucket.  # noqa: E501
        :rtype: str
        """
        return self._role_arn

    @role_arn.setter
    def role_arn(self, role_arn):
        """Sets the role_arn of this V1alpha1S3Bucket.

        RoleARN is the Amazon Resource Name (ARN) of the role to assume.  # noqa: E501

        :param role_arn: The role_arn of this V1alpha1S3Bucket.  # noqa: E501
        :type: str
        """

        self._role_arn = role_arn

    @property
    def secret_key_secret(self):
        """Gets the secret_key_secret of this V1alpha1S3Bucket.  # noqa: E501


        :return: The secret_key_secret of this V1alpha1S3Bucket.  # noqa: E501
        :rtype: kubernetes.client.models.V1SecretKeySelector
        """
        return self._secret_key_secret

    @secret_key_secret.setter
    def secret_key_secret(self, secret_key_secret):
        """Sets the secret_key_secret of this V1alpha1S3Bucket.


        :param secret_key_secret: The secret_key_secret of this V1alpha1S3Bucket.  # noqa: E501
        :type: kubernetes.client.models.V1SecretKeySelector
        """

        self._secret_key_secret = secret_key_secret

    @property
    def use_sdk_creds(self):
        """Gets the use_sdk_creds of this V1alpha1S3Bucket.  # noqa: E501

        UseSDKCreds tells the driver to figure out credentials based on sdk defaults.  # noqa: E501

        :return: The use_sdk_creds of this V1alpha1S3Bucket.  # noqa: E501
        :rtype: bool
        """
        return self._use_sdk_creds

    @use_sdk_creds.setter
    def use_sdk_creds(self, use_sdk_creds):
        """Sets the use_sdk_creds of this V1alpha1S3Bucket.

        UseSDKCreds tells the driver to figure out credentials based on sdk defaults.  # noqa: E501

        :param use_sdk_creds: The use_sdk_creds of this V1alpha1S3Bucket.  # noqa: E501
        :type: bool
        """

        self._use_sdk_creds = use_sdk_creds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1S3Bucket):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
