# coding: utf-8

"""
    Argo

    Argo  # noqa: E501

    The version of the OpenAPI document: v2.7.5
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class V1alpha1WorkflowTemplateSpec(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'workflow_spec': 'V1alpha1WorkflowSpec'
    }

    attribute_map = {
        'workflow_spec': 'workflowSpec'
    }

    def __init__(self, workflow_spec=None):  # noqa: E501
        """V1alpha1WorkflowTemplateSpec - a model defined in OpenAPI"""  # noqa: E501

        self._workflow_spec = None
        self.discriminator = None

        if workflow_spec is not None:
            self.workflow_spec = workflow_spec

    @property
    def workflow_spec(self):
        """Gets the workflow_spec of this V1alpha1WorkflowTemplateSpec.  # noqa: E501


        :return: The workflow_spec of this V1alpha1WorkflowTemplateSpec.  # noqa: E501
        :rtype: V1alpha1WorkflowSpec
        """
        return self._workflow_spec

    @workflow_spec.setter
    def workflow_spec(self, workflow_spec):
        """Sets the workflow_spec of this V1alpha1WorkflowTemplateSpec.


        :param workflow_spec: The workflow_spec of this V1alpha1WorkflowTemplateSpec.  # noqa: E501
        :type: V1alpha1WorkflowSpec
        """

        self._workflow_spec = workflow_spec

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1WorkflowTemplateSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
