/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1SecretKeySelector } from './ioK8sApiCoreV1SecretKeySelector';

/**
* GitArtifact is the location of an git artifact
*/
export class V1alpha1GitArtifact {
    /**
    * InsecureIgnoreHostKey disables SSH strict host key checking during git clone
    */
    'insecureIgnoreHostKey'?: boolean;
    'passwordSecret'?: IoK8sApiCoreV1SecretKeySelector;
    /**
    * Repo is the git repository
    */
    'repo': string;
    /**
    * Revision is the git commit, tag, branch to checkout
    */
    'revision'?: string;
    'sshPrivateKeySecret'?: IoK8sApiCoreV1SecretKeySelector;
    'usernameSecret'?: IoK8sApiCoreV1SecretKeySelector;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "insecureIgnoreHostKey",
            "baseName": "insecureIgnoreHostKey",
            "type": "boolean"
        },
        {
            "name": "passwordSecret",
            "baseName": "passwordSecret",
            "type": "IoK8sApiCoreV1SecretKeySelector"
        },
        {
            "name": "repo",
            "baseName": "repo",
            "type": "string"
        },
        {
            "name": "revision",
            "baseName": "revision",
            "type": "string"
        },
        {
            "name": "sshPrivateKeySecret",
            "baseName": "sshPrivateKeySecret",
            "type": "IoK8sApiCoreV1SecretKeySelector"
        },
        {
            "name": "usernameSecret",
            "baseName": "usernameSecret",
            "type": "IoK8sApiCoreV1SecretKeySelector"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1GitArtifact.attributeTypeMap;
    }
}

