/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DAGTask } from './v1alpha1DAGTask';

/**
* DAGTemplate is a template subtype for directed acyclic graph templates
*/
export class V1alpha1DAGTemplate {
    /**
    * Target are one or more names of targets to execute in a DAG
    */
    'target'?: string;
    /**
    * Tasks are a list of DAG tasks
    */
    'tasks': Array<V1alpha1DAGTask>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "target",
            "baseName": "target",
            "type": "string"
        },
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Array<V1alpha1DAGTask>"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DAGTemplate.attributeTypeMap;
    }
}

