/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Sequence expands a workflow step into numeric range
*/
export class V1alpha1Sequence {
    /**
    * Count is number of elements in the sequence (default: 0). Not to be used with end
    */
    'count'?: string;
    /**
    * Number at which to end the sequence (default: 0). Not to be used with Count
    */
    'end'?: string;
    /**
    * Format is a printf format string to format the value in the sequence
    */
    'format'?: string;
    /**
    * Number at which to start the sequence (default: 0)
    */
    'start'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "string"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "string"
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1Sequence.attributeTypeMap;
    }
}

