/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* ValueFrom describes a location in which to obtain the value to a parameter
*/
export class V1alpha1ValueFrom {
    /**
    * JQFilter expression against the resource object in resource templates
    */
    'jqFilter'?: string;
    /**
    * JSONPath of a resource to retrieve an output parameter value from in resource templates
    */
    'jsonPath'?: string;
    /**
    * Parameter reference to a step or dag task in which to retrieve an output parameter value from (e.g. \'{{steps.mystep.outputs.myparam}}\')
    */
    'parameter'?: string;
    /**
    * Path in the container to retrieve an output parameter value from in container templates
    */
    'path'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "jqFilter",
            "baseName": "jqFilter",
            "type": "string"
        },
        {
            "name": "jsonPath",
            "baseName": "jsonPath",
            "type": "string"
        },
        {
            "name": "parameter",
            "baseName": "parameter",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ValueFrom.attributeTypeMap;
    }
}

