/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1Affinity } from './ioK8sApiCoreV1Affinity';
import { IoK8sApiCoreV1LocalObjectReference } from './ioK8sApiCoreV1LocalObjectReference';
import { IoK8sApiCoreV1PersistentVolumeClaim } from './ioK8sApiCoreV1PersistentVolumeClaim';
import { IoK8sApiCoreV1PodDNSConfig } from './ioK8sApiCoreV1PodDNSConfig';
import { IoK8sApiCoreV1Toleration } from './ioK8sApiCoreV1Toleration';
import { IoK8sApiCoreV1Volume } from './ioK8sApiCoreV1Volume';
import { V1alpha1Arguments } from './v1alpha1Arguments';
import { V1alpha1Template } from './v1alpha1Template';

/**
* WorkflowSpec is the specification of a Workflow.
*/
export class V1alpha1WorkflowSpec {
    /**
    * Optional duration in seconds relative to the workflow start time which the workflow is allowed to run before the controller terminates the workflow. A value of zero is used to terminate a Running workflow
    */
    'activeDeadlineSeconds'?: number;
    'affinity'?: IoK8sApiCoreV1Affinity;
    'arguments'?: V1alpha1Arguments;
    'dnsConfig'?: IoK8sApiCoreV1PodDNSConfig;
    /**
    * Set DNS policy for the pod. Defaults to \"ClusterFirst\". Valid values are \'ClusterFirstWithHostNet\', \'ClusterFirst\', \'Default\' or \'None\'. DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy. To have DNS options set along with hostNetwork, you have to specify DNS policy explicitly to \'ClusterFirstWithHostNet\'.
    */
    'dnsPolicy'?: string;
    /**
    * Entrypoint is a template reference to the starting point of the workflow
    */
    'entrypoint': string;
    /**
    * Host networking requested for this workflow pod. Default to false.
    */
    'hostNetwork'?: boolean;
    /**
    * ImagePullSecrets is a list of references to secrets in the same namespace to use for pulling any images in pods that reference this ServiceAccount. ImagePullSecrets are distinct from Secrets because Secrets can be mounted in the pod, but ImagePullSecrets are only accessed by the kubelet. More info: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
    */
    'imagePullSecrets'?: Array<IoK8sApiCoreV1LocalObjectReference>;
    /**
    * NodeSelector is a selector which will result in all pods of the workflow to be scheduled on the selected node(s). This is able to be overridden by a nodeSelector specified in the template.
    */
    'nodeSelector'?: { [key: string]: string; };
    /**
    * OnExit is a template reference which is invoked at the end of the workflow, irrespective of the success, failure, or error of the primary workflow.
    */
    'onExit'?: string;
    /**
    * Parallelism limits the max total parallel pods that can execute at the same time in a workflow
    */
    'parallelism'?: number;
    /**
    * Priority to apply to workflow pods.
    */
    'podPriority'?: number;
    /**
    * PriorityClassName to apply to workflow pods.
    */
    'podPriorityClassName'?: string;
    /**
    * Priority is used if controller is configured to process limited number of workflows in parallel. Workflows with higher priority are processed first.
    */
    'priority'?: number;
    /**
    * Set scheduler name for all pods. Will be overridden if container/script template\'s scheduler name is set. Default scheduler will be used if neither specified.
    */
    'schedulerName'?: string;
    /**
    * ServiceAccountName is the name of the ServiceAccount to run all pods of the workflow as.
    */
    'serviceAccountName'?: string;
    /**
    * Suspend will suspend the workflow and prevent execution of any future steps in the workflow
    */
    'suspend'?: boolean;
    /**
    * Templates is a list of workflow templates used in a workflow
    */
    'templates': Array<V1alpha1Template>;
    /**
    * Tolerations to apply to workflow pods.
    */
    'tolerations'?: Array<IoK8sApiCoreV1Toleration>;
    /**
    * TTLSecondsAfterFinished limits the lifetime of a Workflow that has finished execution (Succeeded, Failed, Error). If this field is set, once the Workflow finishes, it will be deleted after ttlSecondsAfterFinished expires. If this field is unset, ttlSecondsAfterFinished will not expire. If this field is set to zero, ttlSecondsAfterFinished expires immediately after the Workflow finishes.
    */
    'ttlSecondsAfterFinished'?: number;
    /**
    * VolumeClaimTemplates is a list of claims that containers are allowed to reference. The Workflow controller will create the claims at the beginning of the workflow and delete the claims upon completion of the workflow
    */
    'volumeClaimTemplates'?: Array<IoK8sApiCoreV1PersistentVolumeClaim>;
    /**
    * Volumes is a list of volumes that can be mounted by containers in a workflow.
    */
    'volumes'?: Array<IoK8sApiCoreV1Volume>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "activeDeadlineSeconds",
            "baseName": "activeDeadlineSeconds",
            "type": "number"
        },
        {
            "name": "affinity",
            "baseName": "affinity",
            "type": "IoK8sApiCoreV1Affinity"
        },
        {
            "name": "arguments",
            "baseName": "arguments",
            "type": "V1alpha1Arguments"
        },
        {
            "name": "dnsConfig",
            "baseName": "dnsConfig",
            "type": "IoK8sApiCoreV1PodDNSConfig"
        },
        {
            "name": "dnsPolicy",
            "baseName": "dnsPolicy",
            "type": "string"
        },
        {
            "name": "entrypoint",
            "baseName": "entrypoint",
            "type": "string"
        },
        {
            "name": "hostNetwork",
            "baseName": "hostNetwork",
            "type": "boolean"
        },
        {
            "name": "imagePullSecrets",
            "baseName": "imagePullSecrets",
            "type": "Array<IoK8sApiCoreV1LocalObjectReference>"
        },
        {
            "name": "nodeSelector",
            "baseName": "nodeSelector",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "onExit",
            "baseName": "onExit",
            "type": "string"
        },
        {
            "name": "parallelism",
            "baseName": "parallelism",
            "type": "number"
        },
        {
            "name": "podPriority",
            "baseName": "podPriority",
            "type": "number"
        },
        {
            "name": "podPriorityClassName",
            "baseName": "podPriorityClassName",
            "type": "string"
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number"
        },
        {
            "name": "schedulerName",
            "baseName": "schedulerName",
            "type": "string"
        },
        {
            "name": "serviceAccountName",
            "baseName": "serviceAccountName",
            "type": "string"
        },
        {
            "name": "suspend",
            "baseName": "suspend",
            "type": "boolean"
        },
        {
            "name": "templates",
            "baseName": "templates",
            "type": "Array<V1alpha1Template>"
        },
        {
            "name": "tolerations",
            "baseName": "tolerations",
            "type": "Array<IoK8sApiCoreV1Toleration>"
        },
        {
            "name": "ttlSecondsAfterFinished",
            "baseName": "ttlSecondsAfterFinished",
            "type": "number"
        },
        {
            "name": "volumeClaimTemplates",
            "baseName": "volumeClaimTemplates",
            "type": "Array<IoK8sApiCoreV1PersistentVolumeClaim>"
        },
        {
            "name": "volumes",
            "baseName": "volumes",
            "type": "Array<IoK8sApiCoreV1Volume>"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1WorkflowSpec.attributeTypeMap;
    }
}

