/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1ConfigMapKeySelector } from './ioK8sApiCoreV1ConfigMapKeySelector';
import { IoK8sApiCoreV1SecretKeySelector } from './ioK8sApiCoreV1SecretKeySelector';

/**
* HDFSKrbConfig is auth configurations for Kerberos
*/
export class V1alpha1HDFSKrbConfig {
    'krbCCacheSecret'?: IoK8sApiCoreV1SecretKeySelector;
    'krbConfigConfigMap'?: IoK8sApiCoreV1ConfigMapKeySelector;
    'krbKeytabSecret'?: IoK8sApiCoreV1SecretKeySelector;
    /**
    * KrbRealm is the Kerberos realm used with Kerberos keytab It must be set if keytab is used.
    */
    'krbRealm'?: string;
    /**
    * KrbServicePrincipalName is the principal name of Kerberos service It must be set if either ccache or keytab is used.
    */
    'krbServicePrincipalName'?: string;
    /**
    * KrbUsername is the Kerberos username used with Kerberos keytab It must be set if keytab is used.
    */
    'krbUsername'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "krbCCacheSecret",
            "baseName": "krbCCacheSecret",
            "type": "IoK8sApiCoreV1SecretKeySelector"
        },
        {
            "name": "krbConfigConfigMap",
            "baseName": "krbConfigConfigMap",
            "type": "IoK8sApiCoreV1ConfigMapKeySelector"
        },
        {
            "name": "krbKeytabSecret",
            "baseName": "krbKeytabSecret",
            "type": "IoK8sApiCoreV1SecretKeySelector"
        },
        {
            "name": "krbRealm",
            "baseName": "krbRealm",
            "type": "string"
        },
        {
            "name": "krbServicePrincipalName",
            "baseName": "krbServicePrincipalName",
            "type": "string"
        },
        {
            "name": "krbUsername",
            "baseName": "krbUsername",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1HDFSKrbConfig.attributeTypeMap;
    }
}

