/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1Artifact } from './v1alpha1Artifact';
import { V1alpha1Parameter } from './v1alpha1Parameter';

/**
* Outputs hold parameters, artifacts, and results from a step
*/
export class V1alpha1Outputs {
    /**
    * Artifacts holds the list of output artifacts produced by a step
    */
    'artifacts'?: Array<V1alpha1Artifact>;
    /**
    * Parameters holds the list of output parameters produced by a step
    */
    'parameters'?: Array<V1alpha1Parameter>;
    /**
    * Result holds the result (stdout) of a script template
    */
    'result'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "artifacts",
            "baseName": "artifacts",
            "type": "Array<V1alpha1Artifact>"
        },
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "Array<V1alpha1Parameter>"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1Outputs.attributeTypeMap;
    }
}

