/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1Artifact } from './v1alpha1Artifact';
import { V1alpha1Parameter } from './v1alpha1Parameter';

/**
* Arguments to a template
*/
export class V1alpha1Arguments {
    /**
    * Artifacts is the list of artifacts to pass to the template or workflow
    */
    'artifacts'?: Array<V1alpha1Artifact>;
    /**
    * Parameters is the list of parameters to pass to the template or workflow
    */
    'parameters'?: Array<V1alpha1Parameter>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "artifacts",
            "baseName": "artifacts",
            "type": "Array<V1alpha1Artifact>"
        },
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "Array<V1alpha1Parameter>"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1Arguments.attributeTypeMap;
    }
}

