/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1ValueFrom } from './v1alpha1ValueFrom';

/**
* Parameter indicate a passed string parameter to a service template with an optional default value
*/
export class V1alpha1Parameter {
    /**
    * Default is the default value to use for an input parameter if a value was not supplied
    */
    '_default'?: string;
    /**
    * GlobalName exports an output parameter to the global scope, making it available as \'{{workflow.outputs.parameters.XXXX}} and in workflow.status.outputs.parameters
    */
    'globalName'?: string;
    /**
    * Name is the parameter name
    */
    'name': string;
    /**
    * Value is the literal value to use for the parameter. If specified in the context of an input parameter, the value takes precedence over any passed values
    */
    'value'?: string;
    'valueFrom'?: V1alpha1ValueFrom;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "_default",
            "baseName": "default",
            "type": "string"
        },
        {
            "name": "globalName",
            "baseName": "globalName",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "valueFrom",
            "baseName": "valueFrom",
            "type": "V1alpha1ValueFrom"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1Parameter.attributeTypeMap;
    }
}

