/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1SecretKeySelector } from './ioK8sApiCoreV1SecretKeySelector';

/**
* ArtifactoryArtifact is the location of an artifactory artifact
*/
export class V1alpha1ArtifactoryArtifact {
    'passwordSecret'?: IoK8sApiCoreV1SecretKeySelector;
    /**
    * URL of the artifact
    */
    'url': string;
    'usernameSecret'?: IoK8sApiCoreV1SecretKeySelector;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "passwordSecret",
            "baseName": "passwordSecret",
            "type": "IoK8sApiCoreV1SecretKeySelector"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "usernameSecret",
            "baseName": "usernameSecret",
            "type": "IoK8sApiCoreV1SecretKeySelector"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ArtifactoryArtifact.attributeTypeMap;
    }
}

