/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* ContinueOn defines if a workflow should continue even if a task or step fails/errors. It can be specified if the workflow should continue when the pod errors, fails or both.
*/
export class V1alpha1ContinueOn {
    'error'?: boolean;
    'failed'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "boolean"
        },
        {
            "name": "failed",
            "baseName": "failed",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ContinueOn.attributeTypeMap;
    }
}

