/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* ArchiveStrategy describes how to archive files/directory when saving artifacts
*/
export class V1alpha1ArchiveStrategy {
    /**
    * NoneStrategy indicates to skip tar process and upload the files or directory tree as independent files. Note that if the artifact is a directory, the artifact driver must support the ability to save/load the directory appropriately.
    */
    'none'?: object;
    /**
    * TarStrategy will tar and gzip the file or directory when saving
    */
    'tar'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "none",
            "baseName": "none",
            "type": "object"
        },
        {
            "name": "tar",
            "baseName": "tar",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1ArchiveStrategy.attributeTypeMap;
    }
}

