/**
 * Argo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1ArchiveStrategy } from './v1alpha1ArchiveStrategy';
import { V1alpha1ArtifactoryArtifact } from './v1alpha1ArtifactoryArtifact';
import { V1alpha1GitArtifact } from './v1alpha1GitArtifact';
import { V1alpha1HDFSArtifact } from './v1alpha1HDFSArtifact';
import { V1alpha1HTTPArtifact } from './v1alpha1HTTPArtifact';
import { V1alpha1RawArtifact } from './v1alpha1RawArtifact';
import { V1alpha1S3Artifact } from './v1alpha1S3Artifact';

/**
* Artifact indicates an artifact to place at a specified path
*/
export class V1alpha1Artifact {
    'archive'?: V1alpha1ArchiveStrategy;
    /**
    * ArchiveLogs indicates if the container logs should be archived
    */
    'archiveLogs'?: boolean;
    'artifactory'?: V1alpha1ArtifactoryArtifact;
    /**
    * From allows an artifact to reference an artifact from a previous step
    */
    'from'?: string;
    'git'?: V1alpha1GitArtifact;
    /**
    * GlobalName exports an output artifact to the global scope, making it available as \'{{workflow.outputs.artifacts.XXXX}} and in workflow.status.outputs.artifacts
    */
    'globalName'?: string;
    'hdfs'?: V1alpha1HDFSArtifact;
    'http'?: V1alpha1HTTPArtifact;
    /**
    * mode bits to use on this file, must be a value between 0 and 0777 set when loading input artifacts.
    */
    'mode'?: number;
    /**
    * name of the artifact. must be unique within a template\'s inputs/outputs.
    */
    'name': string;
    /**
    * Make Artifacts optional, if Artifacts doesn\'t generate or exist
    */
    'optional'?: boolean;
    /**
    * Path is the container path to the artifact
    */
    'path'?: string;
    'raw'?: V1alpha1RawArtifact;
    's3'?: V1alpha1S3Artifact;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "archive",
            "baseName": "archive",
            "type": "V1alpha1ArchiveStrategy"
        },
        {
            "name": "archiveLogs",
            "baseName": "archiveLogs",
            "type": "boolean"
        },
        {
            "name": "artifactory",
            "baseName": "artifactory",
            "type": "V1alpha1ArtifactoryArtifact"
        },
        {
            "name": "from",
            "baseName": "from",
            "type": "string"
        },
        {
            "name": "git",
            "baseName": "git",
            "type": "V1alpha1GitArtifact"
        },
        {
            "name": "globalName",
            "baseName": "globalName",
            "type": "string"
        },
        {
            "name": "hdfs",
            "baseName": "hdfs",
            "type": "V1alpha1HDFSArtifact"
        },
        {
            "name": "http",
            "baseName": "http",
            "type": "V1alpha1HTTPArtifact"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "optional",
            "baseName": "optional",
            "type": "boolean"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "raw",
            "baseName": "raw",
            "type": "V1alpha1RawArtifact"
        },
        {
            "name": "s3",
            "baseName": "s3",
            "type": "V1alpha1S3Artifact"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1Artifact.attributeTypeMap;
    }
}

